version: "3.8"
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    environment:
      - BEARER_TOKEN=icVGegYNZ6PMe23g5jNS4dDaQiRhoCTwuzpUfnxjTRPmFFbf6UZLTmeWhvWo9KJpUpoN8239kDhacuRj
    volumes:
      - .:/app
    ports:
      - 4000:4000
    networks:
      - app-network
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.web
      args:
        USERNAME: gordo
        PASSWORD: FCkzTVRe4ETcB9fxrxVM5MSnuM3YizyE4x9uAbQC
    environment:
      - BEARER_TOKEN=icVGegYNZ6PMe23g5jNS4dDaQiRhoCTwuzpUfnxjTRPmFFbf6UZLTmeWhvWo9KJpUpoN8239kDhacuRj
    depends_on:
      - server
    ports:
      - "80:80"
    volumes:
      - ./certs:/etc/letsencrypt
      - ./certbot-data:/data/letsencrypt
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
  #certbot:
  #  image: certbot/certbot
  #  volumes:
  #    - ./certs:/etc/letsencrypt
  #    - ./certbot-data:/data/letsencrypt
  #  depends_on:
  #    - web
  #  entrypoint: /bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'
