version: '3.8'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    volumes:
      - .:/app
    ports:
      - 4000:4000
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "80:80"
