version: "3.8"
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    volumes:
      - .:/app
    ports:
      - 4000:4000
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
      args:
        USERNAME: gordo
        PASSWORD: g00d_p4ssw0rd_123!
    ports:
      - "80:80"
    volumes:
      - ./certs:/etc/letsencrypt
      - ./certbot-data:/data/letsencrypt
  certbot:
    image: certbot/certbot
    volumes:
      - ./certs:/etc/letsencrypt
      - ./certbot-data:/data/letsencrypt
    depends_on:
      - web
    entrypoint: /bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'
