# Use an official Nginx image as a parent image
FROM nginx:alpine

# Install apache2-utils to use htpasswd
RUN apk add --no-cache apache2-utils

# Set environment variables for username and password
# These can be overridden when building the image
ARG USERNAME=admin
ARG PASSWORD=password

# Generate the .htpasswd file
RUN htpasswd -cb /etc/nginx/.htpasswd $USERNAME $PASSWORD

# Copy the static website files into the Nginx server
COPY ./dist /usr/share/nginx/html

# Create Nginx configuration with basic auth for all locations
RUN echo 'server {\
    listen       80;\
    location / {\
        auth_basic           "Restricted";\
        auth_basic_user_file /etc/nginx/.htpasswd;\
        #allow 192.168.2.113;\
        #deny all;\
        root   /usr/share/nginx/html;\
        index  index.html index.htm;\
    }\
}' > /etc/nginx/conf.d/default.conf

# Expose port 80
EXPOSE 80

# Start Nginx when the container has provisioned
CMD ["nginx", "-g", "daemon off;"]