version: "3.8"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.server
    environment:
      - BEARER_TOKEN=icVGegYNZ6PMe23g5jNS4dDaQiRhoCTwuzpUfnxjTRPmFFbf6UZLTmeWhvWo9KJpUpoN8239kDhacuRj
    volumes:
      - .:/app
    ports:
      - "4000:4000"
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.web
      args:
        USERNAME: gordo
        PASSWORD: FCkzTVRe4ETcB9fxrxVM5MSnuM3YizyE4x9uAbQC
    env_file:
      - .env
    depends_on:
      - backend
    ports:
      - "80:80"
    volumes:
      - ./certs:/etc/letsencrypt
      - ./certbot-data:/data/letsencrypt

